name: release
on: 
  push:
    branches:
      - master
jobs:
  release:
    runs-on: windows-latest
    steps:
      - run: echo "$GITHUB_RUN_NUMBER"
      - run: echo %USERPROFILE%
      - run: echo %USERNAME%
      - run: echo $USERNAME
      - run: echo ${USERNAME}
      - run: set
      - run: cmd /c test.cmd
