name: release
on: 
  push:
    branches:
      - master
jobs:
  release:
    runs-on: windows-latest
    steps:
      - run: cmd /c echo %GITHUB_RUN_NUMBER%
      - run: cmd /c echo %USERPROFILE%
      - run: cmd /c echo %USERNAME%
      - run: cmd /c echo %GITHUB_REF%
      - run: cmd /c echo %cd%
      - run: cmd /c set
      - run: cmd /c test.cmd
