name: release
on: 
  push:
    branches:
      - master
jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmd /c ci_release.cmd
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build_out/*.exe"
          tag: "v${GITHUB_RUN_NUMBER}"
          token: ${{ secrets.GITHUB_TOKEN }}

